version: '3'
services:
  db:
    container_name: mood_db
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    container_name: mood
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    environment:
      - EDITOR=vim
    ports:
      - "3000:3000"
    depends_on:
      - db
