version: '3.1'
services:
  db:
    container_name: mood_db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    image: postgres:12.2
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    container_name: mood
    depends_on:
      - db
    environment:
      - APP_URL=http://localhost:32772
      - EDITOR=vim
      - RAILS_TIME_ZONE=Eastern Time (US & Canada)
    expose:
      - 3000
    image: mood
    ports:
      - 32772:3000
    stdin_open: true
    tty: true
    volumes:
      - .:/app
