version: '3.1'
services:
  db:
    container_name: mood_db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    image: postgres:12.2
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    container_name: mood
    depends_on:
      - db
    environment:
      - ALLOWED_ORIGINS=localhost
      - APP_URL=http://localhost:32772
      - EDITOR=vim
      - RAILS_TIME_ZONE=Eastern Time (US & Canada)
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - SENTRY_CLIENT_DSN=${SENTRY_CLIENT_DSN}
      - SENTRY_DSN=${SENTRY_DSN}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - VAPID_SUBJECT=${VAPID_SUBJECT}
    expose:
      - 3000
    image: mood
    ports:
      - 32772:3000
    stdin_open: true
    tty: true
    volumes:
      - .:/app
